// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: content_storage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ContentStorage_CreateUpload_FullMethodName         = "/content_storage.ContentStorage/CreateUpload"
	ContentStorage_GetDownloadUrl_FullMethodName       = "/content_storage.ContentStorage/GetDownloadUrl"
	ContentStorage_ChangeFileVisibility_FullMethodName = "/content_storage.ContentStorage/ChangeFileVisibility"
)

// ContentStorageClient is the client API for ContentStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentStorageClient interface {
	// Create a temporary upload URL
	CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error)
	// Get a presigned download URL for a private file
	GetDownloadUrl(ctx context.Context, in *GetDownloadUrlRequest, opts ...grpc.CallOption) (*GetDownloadUrlResponse, error)
	// Change file visibility
	ChangeFileVisibility(ctx context.Context, in *ChangeVisibilityRequest, opts ...grpc.CallOption) (*ChangeVisibilityResponse, error)
}

type contentStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewContentStorageClient(cc grpc.ClientConnInterface) ContentStorageClient {
	return &contentStorageClient{cc}
}

func (c *contentStorageClient) CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUploadResponse)
	err := c.cc.Invoke(ctx, ContentStorage_CreateUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentStorageClient) GetDownloadUrl(ctx context.Context, in *GetDownloadUrlRequest, opts ...grpc.CallOption) (*GetDownloadUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDownloadUrlResponse)
	err := c.cc.Invoke(ctx, ContentStorage_GetDownloadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentStorageClient) ChangeFileVisibility(ctx context.Context, in *ChangeVisibilityRequest, opts ...grpc.CallOption) (*ChangeVisibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeVisibilityResponse)
	err := c.cc.Invoke(ctx, ContentStorage_ChangeFileVisibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentStorageServer is the server API for ContentStorage service.
// All implementations must embed UnimplementedContentStorageServer
// for forward compatibility
type ContentStorageServer interface {
	// Create a temporary upload URL
	CreateUpload(context.Context, *CreateUploadRequest) (*CreateUploadResponse, error)
	// Get a presigned download URL for a private file
	GetDownloadUrl(context.Context, *GetDownloadUrlRequest) (*GetDownloadUrlResponse, error)
	// Change file visibility
	ChangeFileVisibility(context.Context, *ChangeVisibilityRequest) (*ChangeVisibilityResponse, error)
	mustEmbedUnimplementedContentStorageServer()
}

// UnimplementedContentStorageServer must be embedded to have forward compatible implementations.
type UnimplementedContentStorageServer struct {
}

func (UnimplementedContentStorageServer) CreateUpload(context.Context, *CreateUploadRequest) (*CreateUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUpload not implemented")
}
func (UnimplementedContentStorageServer) GetDownloadUrl(context.Context, *GetDownloadUrlRequest) (*GetDownloadUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDownloadUrl not implemented")
}
func (UnimplementedContentStorageServer) ChangeFileVisibility(context.Context, *ChangeVisibilityRequest) (*ChangeVisibilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeFileVisibility not implemented")
}
func (UnimplementedContentStorageServer) mustEmbedUnimplementedContentStorageServer() {}

// UnsafeContentStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentStorageServer will
// result in compilation errors.
type UnsafeContentStorageServer interface {
	mustEmbedUnimplementedContentStorageServer()
}

func RegisterContentStorageServer(s grpc.ServiceRegistrar, srv ContentStorageServer) {
	s.RegisterService(&ContentStorage_ServiceDesc, srv)
}

func _ContentStorage_CreateUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentStorageServer).CreateUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentStorage_CreateUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentStorageServer).CreateUpload(ctx, req.(*CreateUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentStorage_GetDownloadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentStorageServer).GetDownloadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentStorage_GetDownloadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentStorageServer).GetDownloadUrl(ctx, req.(*GetDownloadUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentStorage_ChangeFileVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeVisibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentStorageServer).ChangeFileVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentStorage_ChangeFileVisibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentStorageServer).ChangeFileVisibility(ctx, req.(*ChangeVisibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentStorage_ServiceDesc is the grpc.ServiceDesc for ContentStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content_storage.ContentStorage",
	HandlerType: (*ContentStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUpload",
			Handler:    _ContentStorage_CreateUpload_Handler,
		},
		{
			MethodName: "GetDownloadUrl",
			Handler:    _ContentStorage_GetDownloadUrl_Handler,
		},
		{
			MethodName: "ChangeFileVisibility",
			Handler:    _ContentStorage_ChangeFileVisibility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content_storage.proto",
}
